version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/SocialMap

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export PYTHONPATH=~/SocialMap
            echo $PYTHONPATH
            echo $PWD
            cd tests
            pytest

  terraformdeploy:
    docker:
      - image: hashicorp/terraform:light
    
    working_directory: ~/SocialMap
    
    steps:
      - checkout
      - run:
          name: run plan command
          command: |
            ls
            echo $PWD
            cd terraform
            yes Okzh0IEjpaODbA.atlasv1.R9NguEwUbdloWdL39Ni34TQaFDKorBfuhmFndByIAODepMPdn6mqtjQjHTNR1HTkJog | terraform login
            ls
            terraform init
            ls
            terraform plan
#            terraform apply -auto-approve
            

workflows:
  version: 2

  my_workflow:
    jobs:
      - build
      - terraformdeploy:
          requires:
            - build
            
            